# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-FileCopyrightText: 2016–2025 The Home Assistant Authors
#
# SPDX-License-Identifier: Apache-2.0
# This file is derived from the structure of:
# https://github.com/home-assistant/core/blob/dev/Dockerfile.dev
#
# Modifications have been made.
FROM mcr.microsoft.com/vscode/devcontainers/base:bookworm
# Need bookworm because oss-cad-suite is compiled with glibc max 3.4.30

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG VERIBLE_VERSION
ARG TARGETARCH

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libyaml-dev \
        git \
        cmake \
        autoconf \
        libreadline-dev \
        libffi-dev \
        tcl8.6-dev \
        # required by verilog module
        universal-ctags \
        # verible deps start
        tar \
        curl \
        ca-certificates \
        # verible deps end
    && apt-get clean \
    # verible start
    && echo "TARGETARCH=${TARGETARCH}" \
    && if [ "${TARGETARCH}" = "amd64" ]; then \
            VERIBLE_ARCH="x86_64"; \
        elif [ "${TARGETARCH}" = "arm64" ]; then \
            VERIBLE_ARCH="arm64"; \
        else \
            echo "Unsupported architecture: ${TARGETARCH}" >&2; \
            exit 1; \
        fi \
    && echo curl -fsSL -o /tmp/verible.tgz \
        "https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-${VERIBLE_ARCH}.tar.gz" \
    && curl -fsSL -o /tmp/verible.tgz \
        "https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-${VERIBLE_ARCH}.tar.gz" \
    && mkdir -p /opt/verible \
    && tar -xzf /tmp/verible.tgz -C /opt/verible --strip-components=1 \
    && rm -f /tmp/verible.tgz \
    && chmod -R a+rX /opt/verible \
    && ln -sf /opt/verible/bin/* /usr/local/bin/ \
    # verible end
    && rm -rf /var/lib/apt/lists/*

# # Add go2rtc binary
# COPY --from=ghcr.io/alexxit/go2rtc:latest /usr/local/bin/go2rtc /bin/go2rtc

WORKDIR /usr/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER vscode

ENV VIRTUAL_ENV="/home/vscode/.local/ha-venv"
RUN --mount=type=bind,source=.python-version,target=.python-version \
    uv python install \
    && uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# # Setup hass-release
# RUN git clone --depth 1 https://github.com/home-assistant/hass-release ~/hass-release \
#     && uv pip install -e ~/hass-release/

# # Install Python dependencies from requirements
# RUN --mount=type=bind,source=requirements.txt,target=requirements.txt \
#     --mount=type=bind,source=homeassistant/package_constraints.txt,target=homeassistant/package_constraints.txt \
#     --mount=type=bind,source=requirements_test.txt,target=requirements_test.txt \
#     --mount=type=bind,source=requirements_test_pre_commit.txt,target=requirements_test_pre_commit.txt \
#     uv pip install -r requirements.txt -r requirements_test.txt

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
