# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
FROM mcr.microsoft.com/vscode/devcontainers/base:bookworm
# Need bookworm because oss-cad-suite is compiled with glibc max 3.4.30

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG VERIBLE_VERSION
ARG TARGETARCH

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libyaml-dev \
        git \
        cmake \
        autoconf \
        libreadline-dev \
        libffi-dev \
        tcl8.6-dev \
        # required by verilog module
        universal-ctags \
        # verible deps start
        tar \
        curl \
        ca-certificates \
        # verible deps end
        # add ccache for verilator
        ccache \
    && apt-get clean \
    # verible start
    && echo "TARGETARCH=${TARGETARCH}" \
    && if [ "${TARGETARCH}" = "amd64" ]; then \
            VERIBLE_ARCH="x86_64"; \
        elif [ "${TARGETARCH}" = "arm64" ]; then \
            VERIBLE_ARCH="arm64"; \
        else \
            echo "Unsupported architecture: ${TARGETARCH}" >&2; \
            exit 1; \
        fi \
    && echo curl -fsSL -o /tmp/verible.tgz \
        "https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-${VERIBLE_ARCH}.tar.gz" \
    && curl -fsSL -o /tmp/verible.tgz \
        "https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-${VERIBLE_ARCH}.tar.gz" \
    && mkdir -p /opt/verible \
    && tar -xzf /tmp/verible.tgz -C /opt/verible --strip-components=1 \
    && rm -f /tmp/verible.tgz \
    && chmod -R a+rX /opt/verible \
    && ln -sf /opt/verible/bin/* /usr/local/bin/ \
    # verible end
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER vscode

ENV VIRTUAL_ENV="/home/vscode/.local/venv"
RUN --mount=type=bind,source=.python-version,target=.python-version \
    uv python install \
    && uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


RUN --mount=type=bind,source=.python-requirements,target=.python-requirements \
    uv pip install -r .python-requirements

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
