#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024–2025 Aaron White <w531t4@gmail.com>
# SPDX-FileCopyrightText: 2016–2025 The Home Assistant Authors
#
# SPDX-License-Identifier: Apache-2.0
# This file is derived from the structure of:
# https://github.com/home-assistant/core/blob/dev/scripts/setup
#
# Modifications have been made.
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/../.."

# Add default vscode settings if not existing
SETTINGS_FILE=./.vscode/settings.json
SETTINGS_TEMPLATE_FILE=./.vscode/settings.default.jsonc
if [ ! -f "$SETTINGS_FILE" ]; then
    echo "Copy $SETTINGS_TEMPLATE_FILE to $SETTINGS_FILE."
    cp "$SETTINGS_TEMPLATE_FILE" "$SETTINGS_FILE"
fi

if [ ! -n "$VIRTUAL_ENV" ]; then
  if [ -x "$(command -v uv)" ]; then
    uv venv .venv
  else
    python3 -m venv .venv
  fi
  source .venv/bin/activate
fi

if ! [ -x "$(command -v uv)" ]; then
  python3 -m pip install uv
fi

src/scripts/bootstrap

pre-commit install

# hass --script ensure_config -c config

# if ! grep -R "logger" config/configuration.yaml >> /dev/null; then
# echo "
# logger:
#   default: info
#   logs:
#     homeassistant.components.cloud: debug
# " >> config/configuration.yaml
# fi