#!/bin/sh
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
# Stop on errors
set -e

cd "$(realpath "$(dirname "$0")/..")"

echo "Installing development dependencies..."

uv pip install \
  -r .python-requirements \
  colorlog \
  --upgrade \
  --config-settings editable_mode=compat

DEFAULT_TOOLCHAIN_TAG=2025-12-18
TOOLCHAIN_TAG=$DEFAULT_TOOLCHAIN_TAG
if [ -f ".toolchain-version" ]; then
  TOOLCHAIN_TAG="$(tr -d ' \t\r\n' < .toolchain-version)"
  if [ -z "$TOOLCHAIN_TAG" ]; then
    TOOLCHAIN_TAG=$DEFAULT_TOOLCHAIN_TAG
  else
    case "$TOOLCHAIN_TAG" in
      [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ;;
      *) TOOLCHAIN_TAG=$DEFAULT_TOOLCHAIN_TAG ;;
    esac
  fi
fi

python3 src/scripts/pull_oss_cad_suite_release.py --tag "$TOOLCHAIN_TAG" \
                                                  --tarball \
                                                  --auto \
                                                  --extract \
                                                  --prune-other-versions \
                                                  --symlink oss-cad-suite \
                                                  --symlink-subdir oss-cad-suite \
                                                  --force-symlink

git submodule init
git submodule update
