#!/bin/sh
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
# Stop on errors
set -e

cd "$(realpath "$(dirname "$0")/..")"

echo "Installing development dependencies..."

uv pip install \
  -r .python-requirements \
  colorlog \
  --upgrade \
  --config-settings editable_mode=compat
python3 src/scripts/pull_oss_cad_suite_release.py --tag 2025-12-18 \
                                                  --tarball \
                                                  --auto \
                                                  --extract \
                                                  --prune-other-versions \
                                                  --symlink oss-cad-suite \
                                                  --symlink-subdir oss-cad-suite \
                                                  --force-symlink

git submodule init
git submodule update
